actor Player
actor Ticker

usecase Feed
usecase Train
usecase Clean
usecase DoNothing

usecase IncreaseHunger
usecase DecreaseHappiness
usecase DecreaseTraining


Player --> Feed
Player --> Train
Player --> Clean
Player --> DoNothing

Ticker --> IncreaseHunger
Ticker --> DecreaseHappiness
Ticker --> DecreaseTraining